### ISSUE TITLE
Native Ads Load issue in native module

### ISSUE THREAD

**Issue by zoobibackups** [ammarahm-ed/react-native-admob-native-ads#126]
Hello i am working on load nativeAd on android native overlay window, load added successfully i received the complete UnifiedNativeAd Object in return, but issue is the when i am Assigning nativeAd object into NativeAdView object so its throw me the error of thread,

its thow me error when i am assigning any data to unifiedNativeAdView Object.
   unifiedNativeAdView.setNativeAd(nativeAd);

Only the original thread that created a view hierarchy can touch its views.
        at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:7753)
        at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1225)
        at android.view.View.requestLayout(View.java:23093)
        at android.view.View.requestLayout(View.java:23093)
        at androidx.constraintlayout.widget.ConstraintLayout.requestLayout(ConstraintLayout.java:3172)
        at android.view.View.requestLayout(View.java:23093)
        at android.view.View.requestLayout(View.java:23093)
        at android.view.ViewGroup.removeAllViews(ViewGroup.java:5518)
        at com.google.android.gms.internal.ads.zzdjg.onSuccess(com.google.android.gms:play-services-ads@@19.7.0:17)
        at com.google.android.gms.internal.ads.zzdzm.run(com.google.android.gms:play-services-ads@@19.7.0:19)
        at com.google.android.gms.internal.ads.zzazu.execute(com.google.android.gms:play-services-ads@@19.7.0:4)
        at com.google.android.gms.internal.ads.zzazt.execute(com.google.android.gms:play-services-ads@@19.7.0:4)
        at com.google.android.gms.internal.ads.zzdyk.zza(com.google.android.gms:play-services-ads@@19.7.0:329)
        at com.google.android.gms.internal.ads.zzdyk.zza(com.google.android.gms:play-services-ads@@19.7.0:265)
        at com.google.android.gms.internal.ads.zzdyk.setFuture(com.google.android.gms:play-services-ads@@19.7.0:170)
        at com.google.android.gms.internal.ads.zzeaf.run(com.google.android.gms:play-services-ads@@19.7.0:12)
        at com.google.android.gms.internal.ads.zzdzd.execute(com.google.android.gms:play-services-ads@@19.7.0:3)
        at com.google.android.gms.internal.ads.zzdyk.zza(com.google.android.gms:play-services-ads@@19.7.0:329)
        at com.google.android.gms.internal.ads.zzdyk.zza(com.google.android.gms:play-services-ads@@19.7.0:265)
        at com.google.android.gms.internal.ads.zzdyk.set(com.google.android.gms:play-services-ads@@19.7.0:156)
        at com.google.android.gms.internal.ads.zzdyp.setResult(com.google.android.gms:play-services-ads@@19.7.0:3)

Kindly guide me on this why its doing issue. i also try to load that data on UI thread but issue is same.
when i get data from the nativeAd object and assign on any textview its work fine. But this Approach is not workable because i could not find any link to redirect on Advertiser Detail.

**Comment by ammarahm-ed** [comment]
I cannot solve the problems not related to this library
