### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.os.Handler.removeCallbacks

### ISSUE THREAD

**Issue by galihlprakoso** [ammarahm-ed/react-native-admob-native-ads#200]
I've checked the android native code. there is null check before calling removeCallbacks but somehow it's still throwing null pointer exception.

This is the full stack trace:
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.os.Handler.removeCallbacks(java.lang.Runnable)' on a null object reference
       at com.ammarahmed.rnadmob.nativeads.RNAdmobNativeView.setNativeAd(RNAdmobNativeView.java:394)
       at com.ammarahmed.rnadmob.nativeads.RNAdmobNativeView$3.onNativeAdLoaded(RNAdmobNativeView.java:146)
       at com.google.android.gms.internal.ads.zzars.zza(com.google.android.gms:play-services-ads-lite@@19.8.0:6)
       at com.google.android.gms.internal.ads.zzagk.zza(com.google.android.gms:play-services-ads-lite@@19.8.0:18)
       at com.google.android.gms.internal.ads.zzgy.onTransact(com.google.android.gms:play-services-ads-base@@19.8.0:13)
       at android.os.Binder.transact(Binder.java:1043)
       at fy.bi(:com.google.android.gms.policy_ads_fdr_dynamite@212104400@212104400057.375149532.375149532:2)
       at com.google.android.gms.ads.internal.formats.client.ak.e(:com.google.android.gms.policy_ads_fdr_dynamite@212104400@212104400057.375149532.375149532)
       at com.google.android.gms.ads.nonagon.ad.nativead.ae.run(:5)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at asu.a(:com.google.android.gms.policy_ads_fdr_dynamite@212104400@212104400057.375149532.375149532)
       at com.google.android.gms.ads.internal.util.f.a(:com.google.android.gms.policy_ads_fdr_dynamite@212104400@212104400057.375149532.375149532:1)
       at asu.dispatchMessage(:com.google.android.gms.policy_ads_fdr_dynamite@212104400@212104400057.375149532.375149532)
       at android.os.Looper.loop(Looper.java:239)
       at android.app.ActivityThread.main(ActivityThread.java:8149)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)
```

It happens on production app.

**Comment by ammarahm-ed** [comment]
I will investigate this

**Comment by ammarahm-ed** [comment]
> I hot fixed this by adding null check on the handler variable:
> 
> RNAdmobNativeView.java -> Line 391 - 420.
> ```
> public void setNativeAd() {
>         if (unifiedNativeAd != null) {
>             if (runnableForMount != null) {
>                 if(handler != null) { <-- here
>                     handler.removeCallbacks(runnableForMount);
>                     runnableForMount = null;
>                 }
>             }
>             runnableForMount = new Runnable() {
>                 @Override
>                 public void run() {
>                     if (nativeAdView != null && unifiedNativeAd != null) {
>                         nativeAdView.setNativeAd(unifiedNativeAd);
> 
>                         if (mediaView != null && nativeAdView.getMediaView()!=null) {
>                             nativeAdView.getMediaView().setMediaContent(unifiedNativeAd.getMediaContent());
>                             if (unifiedNativeAd.getMediaContent().hasVideoContent()) {
>                                 mediaView.setVideoController(unifiedNativeAd.getMediaContent().getVideoController());
>                             }
>                         }
> 
>                     }
>                 }
>             };
>             if (handler != null ) {
>                 handler.postDelayed(runnableForMount, 1000);
>             }
> 
>         }
>     }
> ```

If you can send a PR that would be great.

**Comment by galihlprakoso** [comment]
Sure!

> > I hot fixed this by adding null check on the handler variable:
> > RNAdmobNativeView.java -> Line 391 - 420.
> > ```
> > public void setNativeAd() {
> >         if (unifiedNativeAd != null) {
> >             if (runnableForMount != null) {
> >                 if(handler != null) { <-- here
> >                     handler.removeCallbacks(runnableForMount);
> >                     runnableForMount = null;
> >                 }
> >             }
> >             runnableForMount = new Runnable() {
> >                 @Override
> >                 public void run() {
> >                     if (nativeAdView != null && unifiedNativeAd != null) {
> >                         nativeAdView.setNativeAd(unifiedNativeAd);
> > 
> >                         if (mediaView != null && nativeAdView.getMediaView()!=null) {
> >                             nativeAdView.getMediaView().setMediaContent(unifiedNativeAd.getMediaContent());
> >                             if (unifiedNativeAd.getMediaContent().hasVideoContent()) {
> >                                 mediaView.setVideoController(unifiedNativeAd.getMediaContent().getVideoController());
> >                             }
> >                         }
> > 
> >                     }
> >                 }
> >             };
> >             if (handler != null ) {
> >                 handler.postDelayed(runnableForMount, 1000);
> >             }
> > 
> >         }
> >     }
> > ```
> 
> If you can send a PR that would be great.

Sure then!

**Comment by galihlprakoso** [comment]
But I think it's already fixed by somebody wkwk. Maybe next time!
