### ISSUE TITLE
Execution failed for task ':react-native-admob-native-ads:parseDebugLocalResources'. when trying to run example app

### ISSUE THREAD

**Issue by kyle-belle** [ammarahm-ed/react-native-admob-native-ads#247]
Cloned repo and tried to run example app

i ran npm install in both the root directory and the example directory and got this:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-admob-native-ads:compileDebugJavaWithJavac'.
> directory not found: C:\Users\User 1\Documents\react-native-admob-native-ads\android\build\generated\ap_generated_sources\debug\out

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 30s

    at makeError (C:\Users\User 1\Documents\react-native-admob-native-ads\example\node_modules\execa\index.js:174:9)
    at C:\Users\User 1\Documents\react-native-admob-native-ads\example\node_modules\execa\index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async runOnAllDevices (C:\Users\User 1\Documents\react-native-admob-native-ads\example\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:94:5)
    at async Command.handleAction (C:\Users\User 1\Documents\react-native-admob-native-ads\example\node_modules\react-native\node_modules\@react-native-community\cli\build\index.js:186:9)
info Run CLI with --verbose flag for more details

**Comment by kyle-belle** [comment]
actually. it somehow fixed itself after unplugging my device and plugging it back in

**Comment by kyle-belle** [comment]
but now i get this:

**Comment by ammarahm-ed** [comment]
@kyle-belle I think that the space in your account username in path is causing issue. Try to put the repo in C:\ root and then install node modules then run the project.

**Comment by kyle-belle** [comment]
> @kyle-belle I think that the space in your account username in path is causing issue. Try to put the repo in C:\ root and then install node modules then run the project.

Maybe but I decided not to bother with the example. It works when I use the npm package in my own app
