### ISSUE TITLE
Force Close Fresh Install

### ISSUE THREAD

**Issue by edoofx** [ammarahm-ed/react-native-admob-native-ads#41]
i have 2 new projects with 0.62.2 and 0.61.5, both results is force close.

- npx react-native init abc
- install react-native-admob-native-ads --save
- add AndroidManifest
- npx react-native run-android ( force close before starting splashscreen )

am i missing something?

**Comment by ammarahm-ed** [comment]
add Admob App IDs to your AndroidManifest.xml and info.plist on iOS respectively

**Comment by dan-lee** [comment]
I'm experiencing the same. Not sure if too helpful but my ADB logs say:

```
2020-06-26 15:27:56.554 3820-3957/? E/SoLoader: couldn't find DSO to load: libfbjni.so
    	SoSource 0: com.facebook.soloader.ApkSoSource[root = /data/data/com.myapp/lib-main flags = 1]
    	SoSource 1: com.facebook.soloader.DirectorySoSource[root = /data/app/com.myapp-0zwhmjVxrwR80UNeACugQg==/lib/x86 flags = 0]
    	SoSource 2: com.facebook.soloader.DirectorySoSource[root = /vendor/lib flags = 2]
    	SoSource 3: com.facebook.soloader.DirectorySoSource[root = /system/lib flags = 2]
    	Native lib dir: /data/app/com.myapp-0zwhmjVxrwR80UNeACugQg==/lib/x86
     result: 0
    
    --------- beginning of crash
2020-06-26 15:27:56.558 3820-3957/? E/AndroidRuntime: FATAL EXCEPTION: FlipperEventBaseThread
    Process: com.myapp, PID: 3820
    java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libfbjni.so
    	SoSource 0: com.facebook.soloader.ApkSoSource[root = /data/data/com.myapp/lib-main flags = 1]
    	SoSource 1: com.facebook.soloader.DirectorySoSource[root = /data/app/com.myapp-0zwhmjVxrwR80UNeACugQg==/lib/x86 flags = 0]
    	SoSource 2: com.facebook.soloader.DirectorySoSource[root = /vendor/lib flags = 2]
    	SoSource 3: com.facebook.soloader.DirectorySoSource[root = /system/lib flags = 2]
    	Native lib dir: /data/app/com.myapp-0zwhmjVxrwR80UNeACugQg==/lib/x86
     result: 0
        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:896)
        at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:725)
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:649)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:629)
        at com.facebook.soloader.NativeLoaderToSoLoaderDelegate.loadLibrary(NativeLoaderToSoLoaderDelegate.java:29)
        at com.facebook.soloader.nativeloader.NativeLoader.loadLibrary(NativeLoader.java:51)
        at com.facebook.soloader.nativeloader.NativeLoader.loadLibrary(NativeLoader.java:30)
        at com.facebook.jni.HybridData.<clinit>(HybridData.java:34)
        at com.facebook.flipper.android.FlipperThread.run(FlipperThread.java:25)
```

**Comment by ammarahm-ed** [comment]
The log you have sent does not say anything about this library. Run yarn, clean build folders etc and check your project. Seems above that flipper is causing the crash.

**Comment by dan-lee** [comment]
Yeah I also noticed that, but that's the only thing that changes when I install this library. Just wanted to add this information

**Comment by ammarahm-ed** [comment]
@dan-lee share details about your React Native version / react version & if you are using hermes or JSC. You can also check the example app to see what you might be missing.

**Comment by ammarahm-ed** [comment]
closing due to inactivity
