### ISSUE TITLE
Unable to run example; missing Colors from src/utils.js

### ISSUE THREAD

**Issue by NiwotSmitty** [ammarahm-ed/react-native-admob-native-ads#87]
Hi,

This looks like a great library, so I wanted to give it a try, but when I build/run the example app (iOS), as soon as it starts to run, I get the following errors on the (Javascript) console:

```
error: Error: Unable to resolve module `../utils/Colors` from `node_modules/react-native-admob-native-ads/src/components/StarView.js`: 

None of these files exist:
  * node_modules/react-native-admob-native-ads/src/utils/Colors(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
  * node_modules/react-native-admob-native-ads/src/utils/Colors/index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
    at ModuleResolver.resolveDependency (/Users/gerry/Developer/Misc/react-native-admob-native-ads/example/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (/Users/gerry/Developer/Misc/react-native-admob-native-ads/example/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/Users/gerry/Developer/Misc/react-native-admob-native-ads/example/node_modules/metro/src/node-haste/DependencyGraph.js:287:16)
    at Object.resolve (/Users/gerry/Developer/Misc/react-native-admob-native-ads/example/node_modules/metro/src/lib/transformHelpers.js:267:42)
    at /Users/gerry/Developer/Misc/react-native-admob-native-ads/example/node_modules/metro/src/DeltaBundler/traverseDependencies.js:434:31
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/gerry/Developer/Misc/react-native-admob-native-ads/example/node_modules/metro/src/DeltaBundler/traverseDependencies.js:431:18)
    at /Users/gerry/Developer/Misc/react-native-admob-native-ads/example/node_modules/metro/src/DeltaBundler/traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/gerry/Developer/Misc/react-native-admob-native-ads/example/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)
```

I assume the example library is a little out of date with the current master tip?  Can you either fix, or provide some guidance so I can move forward?

Thanks in advance for your assistance!

**Comment by ammarahm-ed** [comment]
Hey there, I just fixed the example. You can try it out now.
